## CIND830 - Python Programming for Data Science  
### Assignment 2 (10% of the final grade)
### Due on March 15, 2021 11:59 PM

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF.
Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Juputer Notebook.

Use the JupyterHub server on the Google Cloud Platform, provided by your designated instructor, for this assignment. Ensure using Python 3.7.6 release then complete the assignment by inserting your Python code wherever seeing the string "#INSERT YOUR ANSWER HERE."

When you click the `File` button, from the top navigation bar, then select `Export Notebook As ...`,
a document (PDF or HTML format) will be generated that includes
 both the assignment content and the output of any embedded Python code chunks.

Using [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines,
submit **both** the IPYNB and the exported file (PDF or HTML).
Failing to submit both files will be subject to mark deduction.

*****

### Question 1 **[50 pts]**:

**a)** **[15 pts]** Define a function called `isSymmetrical` that takes a string value as a parameter and returns `TRUE` if the given string is Symmetrical. A string is said to be symmetrical if the reverse of the string is the same as string. For example, “madam” is symmetrical, but “water” is not symmetrical.

In [2]:
def isSymmetrical(string):
    reverse = string[::-1]
    if string == reverse:
        return True
    else:
        return False

string = "madam"
print(isSymmetrical(string))

True


**b)** **[5 pts]** Modify the `isSymmetrical` function you created in Q1.a to take any type of data as an input and return `TRUE` if the input is symmetrical. For example, "12321" is symmetrical, but "12345" is not symmetrical.

In [3]:
#INSERT YOUR ANSWER HERE.
def isSymmetrical(string):
    new_string = str(string)
    reverse = new_string[::-1]
    if new_string == reverse:
        return True
    else:
        return False

string = "12321"
print(isSymmetrical(string))

True


**c)** **[10 pts]** Define a function called `isSymmetricalVec` that calls `isSymmetrical` function you updated in Q1.b to take a list of elements and return their results in a list.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns \[`TRUE`, `FALSE`, `TRUE`, `TRUE`, `FALSE`\]

In [5]:
def isSymmetricalVec(arr):
    answers = []
    for i in arr:
        answers.append(isSymmetrical(i))
    return answers

arr = ["1441", "Apple", "radar", "232", "plane"]
print(isSymmetricalVec(arr))

[True, False, True, True, False]


**d)** **[10 pts]** Define a function called `isSymmetricalDict` by modifying the function you created in Q1.c to return the results in a dictionary with their corresponding input elements. \
For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns {"1441": `TRUE`, "Apple": `FALSE`, "radar": `TRUE`, "232": `TRUE`, "plane": `FALSE`\}

In [6]:
def isSymmetricalDict(arr):
    answers = {}
    for i in arr:
        answers[i] = isSymmetrical(i)
    return answers

arr = ["1441", "Apple", "radar", "232", "plane"]
print(isSymmetricalDict(arr))

{'1441': True, 'Apple': False, 'radar': True, '232': True, 'plane': False}


**e)** **[10 pts]** Define a function called `isSymmetricalTuple` by modifying the function you created in Q1.d to traverse the values of the returned dictionary **in reverse order** and return the dictionary keys that has a **`TRUE`** value as a tuple.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns ("232", "radar","1441").

In [7]:
def isSymmetricalTuple(arr):
    answers = []
    for i in reversed(arr):
        if isSymmetrical(i):
        	answers.append(i)
    return tuple(answers)

arr = ["1441", "Apple", "radar", "232", "plane"]
print(isSymmetricalTuple(arr))

('232', 'radar', '1441')


*****



### Question 2 **[80 pts]** :



**a)** **[15 pts]** Define a function called `minSubStr` that takes two string arguments ( S and T ), and returns `TRUE` if the characters of *T* exist in *S*, else returns `FALSE`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns `TRUE` (`T = "ABCD"`, returns `FALSE)`


In [10]:
def minSubStr(S, T):
	for i in T:
		if not i in S:
			return False
	return True

S = "xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx"
T = "ABC"
print(minSubStr(S,T))

True


**b)** **[15 pts]** Modify your `minSubStr` function defined in Q2.a to return the first possible substring (traversing from left) containing all the elements of `T`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"BxxAxxC"`**

In [11]:
def minSubStr(S, T):
	mn = 10000000
	mx = 0
	for i in T:
		for j in range(len(S)):
			if i == S[j]:
				if j < mn:
					mn = j
				if j > mx:
					mx = j
	return S[mn:mx+1]

S = "xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx"
T = "ABC"
print(minSubStr(S,T))

BxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxC


**c)** **[20 pts]** Modify your `minSubStr` function defined in Q2.b to return the shortest substring containing all the elements of T. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxCxB"`**


In [12]:
def minSubStr(S, T):
	mn = 10000000
	answer = ''
	for i in range(len(S)):
		for j in range(i, len(S)):
			temp = S[i:j+1]
			cnt = 0
			for k in T:
				if k in temp:
					cnt += 1
			if cnt == len(T):
				if j - i + 1 < mn:
					mn = j - i + 1
					answer = temp
	return answer

S = "xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx"
T = "ABC"
print(minSubStr(S,T))

AxCxB


**d)** **[30 pts]** modify your `minSubStr` function defined in Q2.c to return the shortest substring containing all the elements of T in order. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxxBxC"`**

In [13]:
def minSubStr(S, T):
	mn = 10000000
	answer = ''
	for i in range(len(S)):
		for j in range(i, len(S)):
			temp = S[i:j+1]
			cnt = 0
			flag = False
			t_index = 0
			temp_index = 0
			while(True):
				if t_index >= len(T):
					flag = True
					break
				if temp_index >= len(temp):
					break
				if T[t_index] == temp[temp_index]:
					t_index += 1
				temp_index += 1
			if flag:
				if j - i + 1 < mn:
					mn = j - i + 1
					answer = temp
	return answer

S = "xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx"
T = "ABC"
print(minSubStr(S,T))

AxxBxC


*****

### Question 3 **[30 pts]**:


**a)** Complete the given code to define three classes, Shape, Oval and Circle. 
- Shape will be the parent class of Oval and Circle. 
- Randomly create ten objects from Oval and Circle classes using the ``for`` loop given below
- Your code should produce correct number of Shapes, Circle and Oval objects. The count of objects should be calculated within the class definitions. 
  - Example output (note that since it is random every time it will be a different number of shapes) \\
  There are  10 random shape objects ['Circle', 'Circle', 'Circle', 'Circle', 'Oval', 'Circle', 'Oval', 'Oval', 'Circle', 'Circle'] \\
	 3 of them are ovals \\
	 7 of them are cirlces \\


In [14]:
# Define Shape class
class Shape:
	count = 0
	def __init__(self):
		self.count += 1

	def get_count(self):
		return self.count

# Define Oval class
class Oval(Shape):
	count = 0
	def __init__(self):
		self.count += 1

	def get_count(self):
		return self.count
# Define Circle class
class Circle(Shape):
	count = 0
	def __init__(self):
		self.count += 1

	def get_count(self):
		return self.count

from random import choice
list_of_shapes = [choice(['Circle', 'Oval']) for x in range(10)]
shape_count = 0
oval_count = 0
circle_count = 0
for shape in list_of_shapes:
  shape_count += 1
  if shape == 'Oval':
    oval = Oval()
    oval_count += 1
  else:
  	circle = Circle()
  	circle_count += 1

print(list_of_shapes)
print('Number of shapes:', shape_count)
print('Number of Ovals:', oval_count)
print('Number of circles:', circle_count)

['Circle', 'Circle', 'Oval', 'Circle', 'Oval', 'Circle', 'Oval', 'Circle', 'Oval', 'Oval']
Number of shapes: 10
Number of Ovals: 5
Number of circles: 5


#### This is the end of assignment 2